# Базовый образ, содержащий среду Java времени выполнения
FROM openjdk:17

# Добавить информацию о владельце
FROM openjdk:11-slim

# Файл jar приложения
ARG JAR_FILE

# Добавить файл jar приложения в контейнер
COPY ${JAR_FILE} app.jar

# запустить приложение
ENTRYPOINT ["java","-jar","/app.jar"]